swagger: '2.0'
info:
  title: Endpooint of pptx2png
  version: '1.0'
host: endpoint-pptx2png-dnb6froqha-uc.a.run.app
schemes:
  - https
produces:
  - application/json
paths:
  /:
    get:
      operationId: 'apply'
      parameters:
        - in: query
          name: args
          type: string
      responses:
        '200':
          description: OK
x-google-backend:
  address: 'https://pptx2png-dnb6froqha-uc.a.run.app'
  protocol: h2
  deadline: 60.0

